server:
  port: 9090

spring:
  application:
    name: demo
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  datasource:
    url: jdbc:postgresql://localhost:5432/vectordb
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 12345678

---
spring:
  config:
    activate:
      on-profile: dev

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

---
spring:
  config:
    activate:
      on-profile: prd

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false
